server:
  port: 8080

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

spring:
  application:
    name: deposit-server-rest
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/deposit?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        register-health-check: true
        health-check-interval: 10s
        health-check-path: /health
        service-name: deposit-server-rest
        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
  thrift:
    server:
      service-id: deposit-server-rpc
      service-model: hsHa
      port: 25000
      worker-queue-capacity: 1000
      hs-ha:
        min-worker-threads: 5
        max-worker-threads: 20
        keep-alived-time: 3
      discovery:
        enabled: true
        host: localhost
        port: 8500
        tags:
          - deposit-server
          - hsHa
        health-check:
          enabled: true
          check-interval: 10
          check-timeout: 3

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.ostenant.rpc.thrift.examples.http.entities

logging:
  level:
    root: INFO
    io:
      ostenant:
        rpc:
          thrift:
            examples:
              mapper: DEBUG