server:
  port: 8081

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        register-health-check: true
        health-check-interval: 10s
        tags:
          - calculator-8081
          - http
        health-check-path: /health
        service-name: thrift-calculator-rest-server
        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
  thrift:
    server:
      service-id: thrift-calculator-rpc-server
      service-model: threadPool
      port: 25001
      worker-queue-capacity: 1000
      thread-pool:
        min-worker-threads: 5
        max-worker-threads: 10
        request-timeout: 5
        keep-alived-time: 2
      discovery:
        enabled: true
        host: localhost
        port: 8500
        tags:
          - threadPool
          - calculator-25001
        health-check:
          enabled: true
          check-interval: 10
          check-timeout: 3
